jumia_dbt:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: diesel-patrol-491520-j8
      dataset: jumia_price_intelligence
      threads: 1
      keyfile: /usr/app/diesel-patrol-491520-j8-16dd83a23f21.json
      location: europe-west1
